galaxy_info:
  author: Daria Kuzmina
  description: install and enable vsftpd; open needed ports, edit selinux context and set vsftpd config to give anon users access to /var/ftp/pub
  company: EPAM
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9
