---
- name: install httpd package
  yum:
      name: httpd
- name: enable httpd service
  service: 
      name: httpd
      state: started
      enabled: true
- name: create welcome page index.html
  template:
      src: templates/index.j2
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'
  notify: 
      - restart httpd
