---
- name: install firewalld package
  yum:
    name: firewalld
- name: enable firewalld service
  service:
    name: firewalld
    state: started
    enabled: true
- name: open port in firewall
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
